version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mibase3
      POSTGRES_USER: kevin
      POSTGRES_PASSWORD: kevin
    ports:
      - "5432:5432"  # Puerto de PostgreSQL expuesto
    
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"    # Puerto de tu aplicación .NET expuesto
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development  # Entorno de desarrollo para tu aplicación .NET
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword"  # Cadena de conexión a PostgreSQL
    links:
      - db
